// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/main": {
    params: {};
  };
  "/close": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create" | "/join" | "/main" | "/close";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
  "routes/main.tsx": {
    id: "routes/main";
    page: "/main";
  };
  "routes/close.tsx": {
    id: "routes/close";
    page: "/close";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/create": typeof import("./app/routes/create.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
  "routes/main": typeof import("./app/routes/main.tsx");
  "routes/close": typeof import("./app/routes/close.tsx");
};